let soundOn=true, audioCtx=null, completed={earth:false,code:false,network:false,data:false};
const rooms={
earth:{icon:"🌍",title:"LA SALA DELLE MACCHINE",desc:"Il computer della sala è in avaria. Quale elemento è indispensabile perché possa eseguire programmi?",choices:["Monitor","CPU","Stampante","Casse audio"],correct:1,hint:"Cerca il componente che esegue le istruzioni."},
code:{icon:"🌬️",title:"IL LINGUAGGIO SEGRETO",desc:"Il computer comunica con due soli simboli. Quale sequenza rappresenta il numero 5 in binario?",choices:["101","111","100","110"],correct:0,hint:"Pensa ai valori 4 + 2 + 1."},
network:{icon:"💧",title:"LA SALA DELLA RETE",desc:"Un PC deve raggiungere un server che si trova nella stessa rete. Quale dispositivo collega più computer all'interno della LAN?",choices:["Switch","Monitor","Tastiera","Scanner"],correct:0,hint:"È il dispositivo che fa da 'incrocio' tra più cavi di rete."},
data:{icon:"🔥",title:"LA CAMERA DEI DATI",desc:"Devi inviare una foto con una connessione molto lenta. Quale versione occupa meno spazio?",choices:["3,2 MB","1,1 MB","350 KB","12 MB"],correct:2,hint:"KB è un'unità più piccola di MB."}
};
function startGame(){show("game");play("start");}
function show(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));document.getElementById(id).classList.add("active")}
function toggleSound(){soundOn=!soundOn;document.getElementById("soundState").textContent=soundOn?"ON":"OFF";if(soundOn)play("click")}
function initAudio(){if(!audioCtx)audioCtx=new (window.AudioContext||window.webkitAudioContext)()}
function play(type){if(!soundOn)return;try{initAudio();let o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type==="error"?"sawtooth":"sine";let f={click:280,ok:620,error:120,unlock:480,start:180,victory:740}[type]||300;o.frequency.value=f;g.gain.setValueAtTime(.0001,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.06,audioCtx.currentTime+.02);g.gain.exponentialRampToValueAtTime(.0001,audioCtx.currentTime+.25);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+.27)}catch(e){}}
function openRoom(key){if(key!=="earth"&&!completed.earth){toast("La prima porta deve essere aperta.");play("error");return}let r=rooms[key];show("room");play("click");document.getElementById("roomContent").innerHTML=`<div class="challenge"><div class="icon">${r.icon}</div><h2>${r.title}</h2><p class="desc">${r.desc}</p><div class="choices">${r.choices.map((c,i)=>`<button class="choice" onclick="answer('${key}',${i},this)">${c}</button>`).join("")}</div><button class="hint" onclick="toast('INDIZIO: ${r.hint}')">✦ CHIEDI UN INDIZIO</button><div id="feedback" class="feedback"></div><div id="codeReveal" class="code-reveal">GEMMA RECUPERATA<br><strong>💎</strong></div></div>`}
function answer(key,i,el){let r=rooms[key];if(completed[key])return;document.querySelectorAll(".choice").forEach(x=>x.disabled=true);if(i===r.correct){el.classList.add("correct");document.getElementById("feedback").className="feedback ok";document.getElementById("feedback").textContent="✓ La porta si apre. Avete trovato la Gemma!";completed[key]=true;document.getElementById("codeReveal").style.display="block";play("ok");flash();setTimeout(()=>unlockNext(key),700)}else{el.classList.add("wrong");document.getElementById("feedback").className="feedback no";document.getElementById("feedback").textContent="✗ La serratura non scatta. Provate a ragionare di nuovo.";play("error");document.querySelectorAll(".choice").forEach(x=>x.disabled=false)}}
function unlockNext(key){let next={earth:"code",code:"network",network:"data",data:"final"}[key];if(next==="final"){document.getElementById("dragonStatus").textContent="SCONFITTO";play("victory");setTimeout(()=>show("victory"),900);return}document.querySelector(`[data-room="${next}"]`).classList.remove("locked");document.getElementById("status-"+next).textContent="✓";document.getElementById("story").textContent="Una nuova porta si è aperta. Il Dungeon vi osserva.";show("game");toast("Una nuova stanza è stata sbloccata!");}
function backMap(){show("game");play("click")}
function flash(){let f=document.getElementById("flash");f.classList.remove("flash");void f.offsetWidth;f.classList.add("flash")}
function toast(t){let x=document.getElementById("toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),2200)}
document.addEventListener("click",e=>{if(e.target.closest("button")){try{initAudio()}catch(_){} }});
